on left click:
	player's target is set
	player's gamemode is not spectator
	set {_item} to player's tool
	if getItemNBTTag({_item},"IBItemsData;Type") = "longsword":
		set {_range} to getItemNBTTag({_item}, "IBItemsData;range")
		set {_blockRange} to distance between player and player's target block
		set {_entityRange} to distance between player and player's target
		if 0.1+{_entityRange} < {_blockRange}:
			{_entityRange} <= {_range}
			make player attack player's target